config/routes.rb
Rails.application.routes.draw do
	# directs logged_in user to a diff. view.  from stack overflow answer
	# https://stackoverflow.com/questions/9339514/different-page-for-logged-in-user-and-not-logged-in-user-at-root/19090936#19090936
	# need to come back and look at where this comes from
	authenticated do
		root 'epicenter#logged_in', as: :authenticated
	end
	root 'movies#index'

  get 'logged_in' => 'epicenter#logged_in'
  post 'logged_in' => 'epicenter#logged_in'

  get 'all_users' => 'epicenter#all_users'

  get 'groovie_friends' => 'epicenter#friends'

  get 'add_friend' => 'epicenter#add_friend'
  get 'remove_friend' => 'epicenter#remove_friend'

	
	get 'index' => "movies#index"
	post 'index' => "movies#index"
  resources :movies
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/movie.rb
class Movie < ApplicationRecord

	has_many :user_movies
	has_many :users, through: :tweet_tags
end

app/models/user.rb
class User < ApplicationRecord
	has_many :user_movies
	has_many :movies, through: :user_movies
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # specifies that the data type for following will be an array.  unable to do this with rails g scaffold or rails g model
  serialize :following, Array
end

app/models/user_movie.rb
class UserMovie < ApplicationRecord
	belongs_to :user
	belongs_to :movie
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :avatar, :following])

    devise_parameter_sanitizer.permit(:account_update, keys: [:username, :avatar, :following])
  end
end

app/controllers/epicenter_controller.rb
class EpicenterController < ApplicationController
  def logged_in
    @movies = Movie.all
    @movie = Movie.new

    if params[:title] != "" && !params[:title].nil? 
      response = HTTParty.get("http://www.omdbapi.com/?t=#{params[:title]}&apikey=#{ENV['omdb_api_key']}&")
      @title = response["Title"]
      @year = response["Year"]
      @genre = response["Genre"]
      @plot = response["Plot"]
      @rotten_value = response["Ratings"][1]["Value"]
      @imdb_value = response["imdbRating"]
      @poster = response["Poster"]
      @website = response["Website"]
    end  	
  end

  def all_users
  	@users = User.all
  end

  def friends
  	@friends = []

  	User.all.each do |friend|
  		if current_user.following.include?(friend.id)
  			@friends.push(friend)
  		end
  	end
  end

  def add_friend
	  current_user.following.push(params[:id].to_i)
  	current_user.save

  	# redirect_to show_user_path(id: params[:id])  	
  	redirect_to all_users_path  	
  end

  def remove_friend
  	current_user.following.delete(params[:id].to_i)
  	current_user.save
  	 # redirect_to show_user_path(id: params[:id])  	
  	redirect_to all_users_path
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: [:show, :edit, :update, :destroy]

  # GET /movies
  # GET /movies.json
  def index
    @movies = Movie.all
    @movie = Movie.new

    if params[:title] != "" && !params[:title].nil? 
      response = HTTParty.get("http://www.omdbapi.com/?t=#{params[:title]}&apikey=#{ENV['omdb_api_key']}&")
      @title = response["Title"]
      @year = response["Year"]
      @genre = response["Genre"]
      @plot = response["Plot"]
      @rotten_value = response["Ratings"][1]["Value"]
      @imdb_value = response["imdbRating"]
      @poster = response["Poster"]
      @website = response["Website"]
    end
  end

  # GET /movies/1
  # GET /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies
  # POST /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        if user_signed_in?
          format.html { redirect_to logged_in_path, notice: 'Movie was successfully created.' }
        end
        format.html { redirect_to movies_path, notice: 'Movie was successfully created.' }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1
  # PATCH/PUT /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to @movie, notice: 'Movie was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1
  # DELETE /movies/1.json
  def destroy
    @movie.destroy
    respond_to do |format|
      format.html { redirect_to movies_url, notice: 'Movie was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_params
      params.require(:movie).permit(:title, :year, :genre, :plot, :poster, :rotten, :imdb, :website)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/epicenter_helper.rb
module EpicenterHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/views/epicenter/all_users.html.erb
<h5>All Groovie Users</h5>

<div class="row">
  <% @users.each do |user| %>
    <div class="col-md-3">
      <div class="card style="width:auto;"">
        <div class="row">
          <div class="col-md-6">
            <%#= image_tag user.avatar.url, width: 50%>
          </div>
          <div class="col-md-6">
            <p>
              <% if current_user.following.include?(user.id) %>
                <%= link_to "Remove", remove_friend_path(id: user.id), class: "btn btn-light btn-sm", id: "remove-btn" %>
              <% else %>
                <% if current_user.id != user.id %>
                  <%= link_to "Add", add_friend_path(id: user.id), class: "btn btn-light btn-sm" %>
                <% end %>
              <% end %>
            </p>
          </div>
        </div>
        <div class="row">
          <div class="col">
          <%#= link_to show_user_path(id: user.id) do %>
            <h5><%= user.username %></h5>
          <%# end %>
          </div>
        </div>
        <div class="row">
          <div class="col">
         <p>
          <%#= link_to "Following", following_path(id: user.id), class: "btn btn-light btn-sm"%></p></div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/epicenter/friends.html.erb
<h4>Your Groovie Friends...</h4>

<div>
	<% @friends.each do |friend| %>
		<p><%= friend.username %></p>
		<p>Movies reviewed: <%= %></p>
		<p>Average rating: <%= %></p>
	<% end %>
</div>

app/views/epicenter/logged_in.html.erb
<h5>Welcome back <%= current_user.username %></h5>

<p>Enter a movie title to begin rating movies.</p>

<br>
<% if @title != nil && @title != "" %>
<div class="card bg-light">
  <div class="row movie-card">
    <div class="col-md-2">
      <%= image_tag @poster, width: 150 %>
    </div>
    <div class="col-md-10">
      <div class="row">
        <div class="col-md-8">
          <p> <%= link_to @title, @website %></p>
          <p>Released: <%= @year %></p>
          <p><%= @genre %></p>
        </div>
        <div class="col-md-4">
          <p>You:</p>
          <p>Your Groovie friends:</p>
          <p>Rotten Tomatoes: <%= @rotten %>%</p>
          <p>imDB: <%= @imdb %></p>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <br> 
          <p><%= @plot %></p>
          <%= render 'form', movie: @movie %>
        </div>
      </div>
    </div>
  </div>
</div>
<br>
<% end %>

<% @movies.each do |movie| %>
<div class="card bg-light">
  <div class="row movie-card">
    <div class="col-md-2">
      <%= image_tag movie.poster, width: 150 %>
    </div>
    <div class="col-md-10">
      <div class="row">
        <div class="col-md-8">
          <p> <%= link_to movie.title, movie.website %></p>
          <p>Released: <%= movie.year %></p>
          <p><%= movie.genre %></p>
        </div>
        <div class="col-md-4">
          <p>You:</p>
          <p>Your Groovie friends:</p> 
          <p>Rotten Tomatoes: <%= movie.rotten %>%</p>
          <p>imDB: <%= movie.imdb %></p>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <br> 
          <p><%= movie.plot %></p>
        </div>
      </div>
    </div>
  </div>
</div>
<br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GroovieMovie</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between">
      <%= link_to "Groovie Movie", root_path, class: "navbar-link" %><span class="sr-only">(current)</span>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <div class="form-inline">
              <%= form_tag index_path do %>
              <%= text_field_tag :title, nil, placeholder: "enter movie title", class: "form-control-sm" %>
              <%= submit_tag "Search", class: "btn btn-light btn-small" %>
              <% end %>
            </div>
            <%#= link_to "Tweet", new_tweet_path, class: "nav-link" %>
          </li>
        </ul>
        <ul class="navbar-nav float-right">
          <% if user_signed_in? %>
            <li class="nav-item dropdown"><span class="caret"></span>
              <a class="nav-link dropdown-toggle" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <%# if current_user.avatar.blank? == false %>
                  <%#= image_tag current_user.avatar.url, size:25%>
                <%# end %>
                <%= current_user.username %>
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "Edit Profile", edit_user_registration_path, class: "dropdown-item" %>
                <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </li>
          <% else %>
          <ul class="navbar-nav">
            <li class="nav-item"><%= link_to "Sign In", new_user_session_path, class: "nav-link" %>
            </li>
          </ul>
          <% end %>
        </ul>
      </div>
    </nav>    
  	<!-- to display error messages from Devise -->

		<p class="alert"><%= alert %></p>
		<div class="container">
    	<%= yield %>
  	</div>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie, local: true) do |form| %>
  <% if movie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
      <% movie.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.hidden_field :title, value: @title %>
  </div>

  <div class="field">
    <%= form.hidden_field :year, value: @year %>
  </div>

  <div class="field">
    <%= form.hidden_field :genre, value: @genre %>
  </div>

  <div class="field">
    <%= form.hidden_field :plot, value: @plot %>
  </div>

  <div class="field">
    <%= form.hidden_field :poster, value: @poster %>
  </div>

  <div class="field">
    <%= form.hidden_field :rotten, value: @rotten_value %>
  </div>

  <div class="field">
    <%= form.hidden_field :imdb, value: @imdb_value %>
  </div>

  <div class="field">
    <%= form.hidden_field :website, value: @website %>
  </div>

  <div class="actions">
    <%= form.submit "Add" %>
  </div>
<% end %>

app/views/movies/edit.html.erb
<h1>Editing Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Show', @movie %> |
<%= link_to 'Back', movies_path %>

app/views/movies/index.html.erb
<p id="notice"><%= notice %></p>


<p>Enter a movie title to begin rating movies.</p>

<br>
<% if @title != nil && @title != "" %>
<div class="card bg-light">
  <div class="row movie-card">
    <div class="col-md-2">
      <%= image_tag @poster, width: 150 %>
    </div>
    <div class="col-md-10">
      <div class="row">
        <div class="col-md-8">
          <p> <%= link_to @title, @website %></p>
          <p>Released: <%= @year %></p>
          <p><%= @genre %></p>
        </div>
        <div class="col-md-4">
          <p>You:</p>
          <p>Your Groovie friends:</p>
          <p>Rotten Tomatoes: <%= @rotten %>%</p>
          <p>imDB: <%= @imdb %></p>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <br> 
          <p><%= @plot %></p>
          <%= render 'form', movie: @movie %>
        </div>
      </div>
    </div>
  </div>
</div>
<br>
<% end %>

<% @movies.each do |movie| %>
<div class="card bg-light">
  <div class="row movie-card">
    <div class="col-md-2">
      <%= image_tag movie.poster, width: 150 %>
    </div>
    <div class="col-md-10">
      <div class="row">
        <div class="col-md-8">
          <p> <%= link_to movie.title, movie.website %></p>
          <p>Released: <%= movie.year %></p>
          <p><%= movie.genre %></p>
        </div>
        <div class="col-md-4">
          <p>You:</p>
          <p>Your Groovie friends:</p> 
          <p>Rotten Tomatoes: <%= movie.rotten %>%</p>
          <p>imDB: <%= movie.imdb %></p>
        </div>
      </div>
      <div class="row">
        <div class="col">
          <br> 
          <p><%= movie.plot %></p>
        </div>
      </div>
    </div>
  </div>
</div>
<br>
<% end %>

app/views/movies/new.html.erb
<h1>New Movie</h1>

<%= render 'form', movie: @movie %>

<%= link_to 'Back', movies_path %>

app/views/movies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @movie.title %>
</p>

<p>
  <strong>Year:</strong>
  <%= @movie.year %>
</p>

<p>
  <strong>Genre:</strong>
  <%= @movie.genre %>
</p>

<p>
  <strong>Plot:</strong>
  <%= @movie.plot %>
</p>

<p>
  <strong>Poster:</strong>
  <%= @movie.poster %>
</p>

<p>
  <strong>Rotten:</strong>
  <%= @movie.rotten %>
</p>

<p>
  <strong>Imdb:</strong>
  <%= @movie.imdb %>
</p>

<p>
  <strong>Website:</strong>
  <%= @movie.website %>
</p>

<%= link_to 'Edit', edit_movie_path(@movie) %> |
<%= link_to 'Back', movies_path %>